### ISSUE TITLE
Feature Request: Hide module when nothing ist playing

### ISSUE THREAD

**Issue by requiemmg** [skuethe/MMM-Spotify#179] opened 2022-01-07 10:58 UTC
Title says it all: Hide the module when nothing is playing, both for minibar and normal mode (and free the space the module needs when visible!)

**Comment by skuethe** [comment] 2022-01-07 12:44
Thank you for creating this issue. I will close it, as it is a duplicate of #176

**Closed as completed by skuethe** 2022-01-07 12:44 UTC
Labels: duplicate
